import Head from 'next/head';
import { getPVAResults } from '../helpers/api-util';
import styles from '../styles/Home.module.css';
import { Property } from '../types/properties';

interface PropertyProps {
  properties: Property[];
}

const Home = (props: PropertyProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PVW POC - Search Results</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {props.properties.map((property: Property) => {
            return (
              <li key={property.id}>
                {property.propertyTypeFullDescription}
              </li>
            );
          })}
        </ul>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const properties: Property[] = await getPVAResults();
  return {
    props: {
      properties,
    },
    revalidate: 60,
  };
};

export default Home;
